name: democode pages
description: Published pages for democode
theme: jekyll-theme-primer
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
